Feature/changelog topic create
quixio/quix-streams pull request #258
Opened 2023-12-07 22:05 UTC by tim-quix

Note, this is a draft and I'm still cleaning/finalizing some things!

## Scope/Goal:

The outcome of this PR is two main things:

1. Consolidating topic management (especially quix vs non-quix topics)
2. Adding the auto-creation of changelog topics (made easier by the above)

### Details

#### Organization-related

There were numerous things shuffled around and cleaned up as part of this, most
of which was consolidated to below:

- New `TopicKafkaConfig` object
  - stores all topic attributes (partition, rep_factor) and optional 
    configs necessary to create a topic.
  - Typically stored on `Topic.kafka_configs` but is used in other spots
  - Keeps track of whether the topic is `Quix` or not and manages 
    kafka-related configs accordingly

- New `TopicAdmin` object
  - created/used by `Application` to manage all topic-related things, including:
    - storing and generating all `Topic` objects
    - auto-creating topics
    - getting/inspecting existing topics
    - helps keep track of whether resources are quix-related or not
  - Generally not intended to be managed by user

#### Changelog-related

- `StateStoreManager`
  - Now uses `TopicAdmin` to generate changelog `Topic` objects
    - `TopicAdmin` passed from `Application`
    - If changelogs are disabled, will not have a `TopicAdmin` object

## Intention behind organizational changes

In current state, managing Quix vs non-Quix topics is a bit of a pain, 
especially since they have different default configurations, and are not
generated in the same fashion (there's currently no sanctioned way to 
auto-create topics for a non-Quix `Application` with desired settings).

This matter is only further compounded with managing "changelog" topics, which
are intended to largely be "behind-the-scenes" and have strict requirements
around how they are configured (including dependencies on other topics!)

To not have users have to manage this no matter their platform, I went ahead 
and implemented a more generalized approach to topic creation. 

While still needing some more robust behavior around creation and validation for
non-Quix apps, this accomplished the following:

- maintain one location for default topic config values (`TopicKafkaConfig`)
- keep `Topic` objects in one place (`TopicAdmin`)
- keep functionality around managing topics in 1 place (`TopicAdmin`)
- tracking whether a `Topic` must use the Quix API or not for creation

I still might shuffle/split some functionality out later, but overall I think
this is a good foundation.

## Intention behind "changelog" topic additions

With the above implemented, changelog-related work was minimal. 

Added the ability to turn off changelog topic usage from the `Application` 
itself, which is just handed to `StateStoreManager`. 

Speaking of, since state and changelog topics are closely intertwined, I figured
a good foundation would be giving the `StateStoreManager` access to the
`TopicAdmin` object which basically manages all changelog topic work (
`StateStoreManager` only has to call `TopicAdmin.changelog_topic()` right after
it generates a `Store`.).

### Final Thoughts

I debated creating an even higher level state-related manager to keep the 
"db"-related state management/functionality separate from the 
"kafka/changelog"-related (thus leaving `StateStoreManager` untouched/independent), 
but it felt a bit overkill: 
- there are gonna be other objects generated by `StateStoreManager` that will 
  also need to do something with these changelog topics anyway, which may also 
  only require similar minor additions.
- you can easily turn off changelogs, skipping the additional functionality
- Not many people are probably going to use storage without the changelog,
  so I think coupling the functionality somewhat tightly is probably fine.
- There's already a lot going on with state as-is, I don't think we need more 
  abstraction if we can help it.

As I work on the next story, those feelings might change depending on the needs
that arise, but I'm confident either way that this is enough of a foundation
to work from.

2023-12-11 10:12 UTC, daniil-quix requested changes
Hey Tim, the overall approach looks good so far, but I'd change some details:

**Naming:**
- `TopicAdmin` -> `TopicManager`. "Manager" seems like a better description of what's going on in the class
- `_admin` -> `_admin_client` - the property returns `AdminClient`
- `TopicKafkaConfigs` -> `TopicConfig`

**Composition:**
- It seems to me we need a common interface for the TopicManager, but two different implementations: for Quix and non-Quix apps. 
There are too many `if`'s here and there handling different logic, and probably more will come in the future (e.g. different error handling). 
Having one big class will also complicate testing and debugging.

Also, see other comments

2023-12-11 10:12 UTC, daniil-quix commented on quixstreams/models/topics.py
> +            raise Exception(
The exception class must be specific. Raising plain `Exception` is not a good practice

2023-12-11 10:12 UTC, daniil-quix commented on quixstreams/kafka/admin.py
> +        base_optionals = {} if self.has_quix_builder else {"cleanup.policy": "compact"}
I'd consider expanding "optionals" into the individual named parameters if it's possible.
(In other places too)

If not, let's rename it to `extra` like it's done in Producer and Consumer classes

2024-01-10 22:11 UTC, tim-quix commented
The code has significantly changed since it was last reviewed, so closing this. As such, opened a new PR, plus changed the  branch name (put all recovery-related changes under `feature/recovery/`).

2024-01-10 22:11 UTC, closed without merging